# Setup
title:               ML papers
tagline:             'One a week'
description:         'PhD Research'
url:                 https://alkaluqman.github.io/MLpapers
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alka
  giturl:            'https://github.com/users/alkaluqman/projects/1'
  email:             alka.luqman@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
